name: Log Repository Info

# Trigger the workflow on push events to the YAML file
on:
  push:
    paths:
      - .github/workflows/main.yml

jobs:
  log-repo-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log Repository Owner and Name
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          node << 'EOF'
          const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
          console.log(`Owner: ${owner}`);
          console.log(`Repo: ${repo}`);
          EOF